name: Deploying weatherForecastApp on GithubPages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: 
      - opened
      - reopened

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Using Node.js version 18

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # Make sure this matches your build script in package.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Make sure this matches your actual build output directory
