name: Deploy weatherForecastApp to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

permissions:
  contents: write  # Grant write permission to push changes to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Update to v3
        with:
          node-version: '18'  # Use the appropriate version you're targeting

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Update to v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Replace with your build output directory
          branch: gh-pages
